# Generated by Django 5.1.3 on 2024-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
