# Generated by Django 5.1.3 on 2024-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_empleados_user_alter_empleados_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='user',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rol',
            field=models.CharField(choices=[('Empleados', 'Empleados'), ('Encargado', 'Encargado')], default='Empleados', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
